M48
; DRILL file {KiCad 9.0.6} date 2026-01-18T01:14:11+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-18T01:14:11+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X68.5Y-85.58
X78.66Y-85.58
T2
X67.5Y-40.0
X84.55Y-40.0
X90.55Y-40.0
X107.6Y-40.0
T3
X73.58Y-85.58
M30
