M48
; DRILL file {KiCad 9.0.6} date 2025-12-28T20:24:03+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-28T20:24:03+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X49.8Y-62.5
X66.85Y-62.5
X72.9Y-62.5
X89.95Y-62.5
X96.0Y-62.5
X113.05Y-62.5
M30
