M48
; DRILL file {KiCad 9.0.5} date 2025-11-23T07:48:09+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-23T07:48:09+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X150.0Y-97.46
X150.0Y-100.0
X150.0Y-102.54
T2
X145.0Y-95.0
X145.0Y-100.0
X145.0Y-105.0
M30
